site_name: Guide to Business Assistance and Incentives
nav:
    - Small Business: index.md
    - About: about.md
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'black'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'images/logo.png'
  feature:
    tabs: false
